# Generated by Django 2.1.dev20180407215333 on 2018-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
