# Generated by Django 2.1.dev20180407215333 on 2018-05-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNA', '0006_auto_20180513_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_publisher', to='SNA.User'),
        ),
    ]
