# Generated by Django 2.1.dev20180407215333 on 2018-05-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNA', '0008_auto_20180513_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_group', to='SNA.Group'),
        ),
    ]
