# Generated by Django 2.1.dev20180407215333 on 2018-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNA', '0009_auto_20180513_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='scope',
            field=models.CharField(choices=[('P', 'post'), ('C', 'comment')], default='P', max_length=1, null=True),
        ),
    ]
